//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCustomerPurchase
    {
        public int CustomerPurchaseID { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> Barcode { get; set; }
    
        public virtual PCustomer PCustomer { get; set; }
        public virtual PProduct PProduct { get; set; }
    }
}
