//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class POrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public POrder()
        {
            this.POrderItems = new HashSet<POrderItem>();
        }
    
        public int OrderNumber { get; set; }
        public decimal TotalPrice { get; set; }
        public decimal TotalDiscount { get; set; }
        public decimal TotalTax { get; set; }
        public decimal CardPayment { get; set; }
        public decimal CashPayment { get; set; }
        public Nullable<int> PoitRedeem { get; set; }
        public Nullable<int> PointEarned { get; set; }
        public System.DateTime OrdeDate { get; set; }
        public Nullable<int> IsReturned { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> Username { get; set; }
    
        public virtual PCustomer PCustomer { get; set; }
        public virtual PEmployee PEmployee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POrderItem> POrderItems { get; set; }
    }
}
