//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bpatel405Entities : DbContext
    {
        public bpatel405Entities()
            : base("name=bpatel405Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PBrand> PBrands { get; set; }
        public virtual DbSet<PCategory> PCategories { get; set; }
        public virtual DbSet<PCustomer> PCustomers { get; set; }
        public virtual DbSet<PCustomerPurchase> PCustomerPurchases { get; set; }
        public virtual DbSet<PEmployee> PEmployees { get; set; }
        public virtual DbSet<POrder> POrders { get; set; }
        public virtual DbSet<POrderItem> POrderItems { get; set; }
        public virtual DbSet<PProduct> PProducts { get; set; }
    }
}
